<?php

namespace ProtoneMedia\LaravelMixins\Database;

class CountriesInDutch
{
    private array $data = [
        ["name" => "Afghanistan", "alpha2" => "af", "alpha3" => "afg"],
        ["name" => "Åland", "alpha2" => "ax", "alpha3" => "ala"],
        ["name" => "Albanië", "alpha2" => "al", "alpha3" => "alb"],
        ["name" => "Algerije", "alpha2" => "dz", "alpha3" => "dza"],
        ["name" => "Amerikaanse Maagdeneilanden", "alpha2" => "vi", "alpha3" => "vir"],
        ["name" => "Amerikaans-Samoa", "alpha2" => "as", "alpha3" => "asm"],
        ["name" => "Andorra", "alpha2" => "ad", "alpha3" => "and"],
        ["name" => "Angola", "alpha2" => "ao", "alpha3" => "ago"],
        ["name" => "Anguilla", "alpha2" => "ai", "alpha3" => "aia"],
        ["name" => "Antarctica", "alpha2" => "aq", "alpha3" => "ata"],
        ["name" => "Antigua en Barbuda", "alpha2" => "ag", "alpha3" => "atg"],
        ["name" => "Argentinië", "alpha2" => "ar", "alpha3" => "arg"],
        ["name" => "Armenië", "alpha2" => "am", "alpha3" => "arm"],
        ["name" => "Aruba", "alpha2" => "aw", "alpha3" => "abw"],
        ["name" => "Australië", "alpha2" => "au", "alpha3" => "aus"],
        ["name" => "Azerbeidzjan", "alpha2" => "az", "alpha3" => "aze"],
        ["name" => "Bahama's", "alpha2" => "bs", "alpha3" => "bhs"],
        ["name" => "Bahrein", "alpha2" => "bh", "alpha3" => "bhr"],
        ["name" => "Bangladesh", "alpha2" => "bd", "alpha3" => "bgd"],
        ["name" => "Barbados", "alpha2" => "bb", "alpha3" => "brb"],
        ["name" => "België", "alpha2" => "be", "alpha3" => "bel"],
        ["name" => "Belize", "alpha2" => "bz", "alpha3" => "blz"],
        ["name" => "Benin", "alpha2" => "bj", "alpha3" => "ben"],
        ["name" => "Bermuda", "alpha2" => "bm", "alpha3" => "bmu"],
        ["name" => "Bhutan", "alpha2" => "bt", "alpha3" => "btn"],
        ["name" => "Bolivia", "alpha2" => "bo", "alpha3" => "bol"],
        ["name" => "Caribisch Nederland", "alpha2" => "bq", "alpha3" => "bes"],
        ["name" => "Bosnië en Herzegovina", "alpha2" => "ba", "alpha3" => "bih"],
        ["name" => "Botswana", "alpha2" => "bw", "alpha3" => "bwa"],
        ["name" => "Bouveteiland", "alpha2" => "bv", "alpha3" => "bvt"],
        ["name" => "Brazilië", "alpha2" => "br", "alpha3" => "bra"],
        ["name" => "Britse Maagdeneilanden", "alpha2" => "vg", "alpha3" => "vgb"],
        ["name" => "Brits Indische Oceaanterritorium", "alpha2" => "io", "alpha3" => "iot"],
        ["name" => "Brunei", "alpha2" => "bn", "alpha3" => "brn"],
        ["name" => "Bulgarije", "alpha2" => "bg", "alpha3" => "bgr"],
        ["name" => "Burkina Faso", "alpha2" => "bf", "alpha3" => "bfa"],
        ["name" => "Burundi", "alpha2" => "bi", "alpha3" => "bdi"],
        ["name" => "Cambodja", "alpha2" => "kh", "alpha3" => "khm"],
        ["name" => "Canada", "alpha2" => "ca", "alpha3" => "can"],
        ["name" => "Centraal-Afrikaanse Republiek", "alpha2" => "cf", "alpha3" => "caf"],
        ["name" => "Chili", "alpha2" => "cl", "alpha3" => "chl"],
        ["name" => "China", "alpha2" => "cn", "alpha3" => "chn"],
        ["name" => "Christmaseiland", "alpha2" => "cx", "alpha3" => "cxr"],
        ["name" => "Cocoseilanden", "alpha2" => "cc", "alpha3" => "cck"],
        ["name" => "Colombia", "alpha2" => "co", "alpha3" => "col"],
        ["name" => "Comoren", "alpha2" => "km", "alpha3" => "com"],
        ["name" => "Congo-Brazzaville", "alpha2" => "cg", "alpha3" => "cog"],
        ["name" => "Congo-Kinshasa", "alpha2" => "cd", "alpha3" => "cod"],
        ["name" => "Cookeilanden", "alpha2" => "ck", "alpha3" => "cok"],
        ["name" => "Costa Rica", "alpha2" => "cr", "alpha3" => "cri"],
        ["name" => "Cuba", "alpha2" => "cu", "alpha3" => "cub"],
        ["name" => "Curaçao", "alpha2" => "cw", "alpha3" => "cuw"],
        ["name" => "Cyprus", "alpha2" => "cy", "alpha3" => "cyp"],
        ["name" => "Denemarken", "alpha2" => "dk", "alpha3" => "dnk"],
        ["name" => "Djibouti", "alpha2" => "dj", "alpha3" => "dji"],
        ["name" => "Dominica", "alpha2" => "dm", "alpha3" => "dma"],
        ["name" => "Dominicaanse Republiek", "alpha2" => "do", "alpha3" => "dom"],
        ["name" => "Duitsland", "alpha2" => "de", "alpha3" => "deu"],
        ["name" => "Ecuador", "alpha2" => "ec", "alpha3" => "ecu"],
        ["name" => "Egypte", "alpha2" => "eg", "alpha3" => "egy"],
        ["name" => "El Salvador", "alpha2" => "sv", "alpha3" => "slv"],
        ["name" => "Equatoriaal-Guinea", "alpha2" => "gq", "alpha3" => "gnq"],
        ["name" => "Eritrea", "alpha2" => "er", "alpha3" => "eri"],
        ["name" => "Estland", "alpha2" => "ee", "alpha3" => "est"],
        ["name" => "Ethiopië", "alpha2" => "et", "alpha3" => "eth"],
        ["name" => "Faeröer", "alpha2" => "fo", "alpha3" => "fro"],
        ["name" => "Falklandeilanden", "alpha2" => "fk", "alpha3" => "flk"],
        ["name" => "Fiji", "alpha2" => "fj", "alpha3" => "fji"],
        ["name" => "Filipijnen", "alpha2" => "ph", "alpha3" => "phl"],
        ["name" => "Finland", "alpha2" => "fi", "alpha3" => "fin"],
        ["name" => "Frankrijk", "alpha2" => "fr", "alpha3" => "fra"],
        ["name" => "Franse Zuidelijke en Antarctische Gebieden", "alpha2" => "tf", "alpha3" => "atf"],
        ["name" => "Frans-Guyana", "alpha2" => "gf", "alpha3" => "guf"],
        ["name" => "Frans-Polynesië", "alpha2" => "pf", "alpha3" => "pyf"],
        ["name" => "Gabon", "alpha2" => "ga", "alpha3" => "gab"],
        ["name" => "Gambia", "alpha2" => "gm", "alpha3" => "gmb"],
        ["name" => "Georgië", "alpha2" => "ge", "alpha3" => "geo"],
        ["name" => "Ghana", "alpha2" => "gh", "alpha3" => "gha"],
        ["name" => "Gibraltar", "alpha2" => "gi", "alpha3" => "gib"],
        ["name" => "Grenada", "alpha2" => "gd", "alpha3" => "grd"],
        ["name" => "Griekenland", "alpha2" => "gr", "alpha3" => "grc"],
        ["name" => "Groenland", "alpha2" => "gl", "alpha3" => "grl"],
        ["name" => "Guadeloupe", "alpha2" => "gp", "alpha3" => "glp"],
        ["name" => "Guam", "alpha2" => "gu", "alpha3" => "gum"],
        ["name" => "Guatemala", "alpha2" => "gt", "alpha3" => "gtm"],
        ["name" => "Guernsey", "alpha2" => "gg", "alpha3" => "ggy"],
        ["name" => "Guinee", "alpha2" => "gn", "alpha3" => "gin"],
        ["name" => "Guinee-Bissau", "alpha2" => "gw", "alpha3" => "gnb"],
        ["name" => "Guyana", "alpha2" => "gy", "alpha3" => "guy"],
        ["name" => "Haïti", "alpha2" => "ht", "alpha3" => "hti"],
        ["name" => "Heard en McDonaldeilanden", "alpha2" => "hm", "alpha3" => "hmd"],
        ["name" => "Honduras", "alpha2" => "hn", "alpha3" => "hnd"],
        ["name" => "Hongarije", "alpha2" => "hu", "alpha3" => "hun"],
        ["name" => "Hongkong", "alpha2" => "hk", "alpha3" => "hkg"],
        ["name" => "Ierland", "alpha2" => "ie", "alpha3" => "irl"],
        ["name" => "IJsland", "alpha2" => "is", "alpha3" => "isl"],
        ["name" => "India", "alpha2" => "in", "alpha3" => "ind"],
        ["name" => "Indonesië", "alpha2" => "id", "alpha3" => "idn"],
        ["name" => "Irak", "alpha2" => "iq", "alpha3" => "irq"],
        ["name" => "Iran", "alpha2" => "ir", "alpha3" => "irn"],
        ["name" => "Israël", "alpha2" => "il", "alpha3" => "isr"],
        ["name" => "Italië", "alpha2" => "it", "alpha3" => "ita"],
        ["name" => "Ivoorkust", "alpha2" => "ci", "alpha3" => "civ"],
        ["name" => "Jamaica", "alpha2" => "jm", "alpha3" => "jam"],
        ["name" => "Japan", "alpha2" => "jp", "alpha3" => "jpn"],
        ["name" => "Jemen", "alpha2" => "ye", "alpha3" => "yem"],
        ["name" => "Jersey", "alpha2" => "je", "alpha3" => "jey"],
        ["name" => "Jordanië", "alpha2" => "jo", "alpha3" => "jor"],
        ["name" => "Kaaimaneilanden", "alpha2" => "ky", "alpha3" => "cym"],
        ["name" => "Kaapverdië", "alpha2" => "cv", "alpha3" => "cpv"],
        ["name" => "Kameroen", "alpha2" => "cm", "alpha3" => "cmr"],
        ["name" => "Kazachstan", "alpha2" => "kz", "alpha3" => "kaz"],
        ["name" => "Kenia", "alpha2" => "ke", "alpha3" => "ken"],
        ["name" => "Kirgizië", "alpha2" => "kg", "alpha3" => "kgz"],
        ["name" => "Kiribati", "alpha2" => "ki", "alpha3" => "kir"],
        ["name" => "Kleine afgelegen eilanden van de Verenigde Staten", "alpha2" => "um", "alpha3" => "umi"],
        ["name" => "Koeweit", "alpha2" => "kw", "alpha3" => "kwt"],
        ["name" => "Kroatië", "alpha2" => "hr", "alpha3" => "hrv"],
        ["name" => "Laos", "alpha2" => "la", "alpha3" => "lao"],
        ["name" => "Lesotho", "alpha2" => "ls", "alpha3" => "lso"],
        ["name" => "Letland", "alpha2" => "lv", "alpha3" => "lva"],
        ["name" => "Libanon", "alpha2" => "lb", "alpha3" => "lbn"],
        ["name" => "Liberia", "alpha2" => "lr", "alpha3" => "lbr"],
        ["name" => "Libië", "alpha2" => "ly", "alpha3" => "lby"],
        ["name" => "Liechtenstein", "alpha2" => "li", "alpha3" => "lie"],
        ["name" => "Litouwen", "alpha2" => "lt", "alpha3" => "ltu"],
        ["name" => "Luxemburg", "alpha2" => "lu", "alpha3" => "lux"],
        ["name" => "Macau", "alpha2" => "mo", "alpha3" => "mac"],
        ["name" => "Macedonië", "alpha2" => "mk", "alpha3" => "mkd"],
        ["name" => "Madagaskar", "alpha2" => "mg", "alpha3" => "mdg"],
        ["name" => "Malawi", "alpha2" => "mw", "alpha3" => "mwi"],
        ["name" => "Maldiven", "alpha2" => "mv", "alpha3" => "mdv"],
        ["name" => "Maleisië", "alpha2" => "my", "alpha3" => "mys"],
        ["name" => "Mali", "alpha2" => "ml", "alpha3" => "mli"],
        ["name" => "Malta", "alpha2" => "mt", "alpha3" => "mlt"],
        ["name" => "Man", "alpha2" => "im", "alpha3" => "imn"],
        ["name" => "Marokko", "alpha2" => "ma", "alpha3" => "mar"],
        ["name" => "Marshalleilanden", "alpha2" => "mh", "alpha3" => "mhl"],
        ["name" => "Martinique", "alpha2" => "mq", "alpha3" => "mtq"],
        ["name" => "Mauritanië", "alpha2" => "mr", "alpha3" => "mrt"],
        ["name" => "Mauritius", "alpha2" => "mu", "alpha3" => "mus"],
        ["name" => "Mayotte", "alpha2" => "yt", "alpha3" => "myt"],
        ["name" => "Mexico", "alpha2" => "mx", "alpha3" => "mex"],
        ["name" => "Micronesia", "alpha2" => "fm", "alpha3" => "fsm"],
        ["name" => "Moldavië", "alpha2" => "md", "alpha3" => "mda"],
        ["name" => "Monaco", "alpha2" => "mc", "alpha3" => "mco"],
        ["name" => "Mongolië", "alpha2" => "mn", "alpha3" => "mng"],
        ["name" => "Montenegro", "alpha2" => "me", "alpha3" => "mne"],
        ["name" => "Montserrat", "alpha2" => "ms", "alpha3" => "msr"],
        ["name" => "Mozambique", "alpha2" => "mz", "alpha3" => "moz"],
        ["name" => "Myanmar", "alpha2" => "mm", "alpha3" => "mmr"],
        ["name" => "Namibië", "alpha2" => "na", "alpha3" => "nam"],
        ["name" => "Nauru", "alpha2" => "nr", "alpha3" => "nru"],
        ["name" => "Nederland", "alpha2" => "nl", "alpha3" => "nld"],
        ["name" => "Nepal", "alpha2" => "np", "alpha3" => "npl"],
        ["name" => "Nicaragua", "alpha2" => "ni", "alpha3" => "nic"],
        ["name" => "Nieuw-Caledonië", "alpha2" => "nc", "alpha3" => "ncl"],
        ["name" => "Nieuw-Zeeland", "alpha2" => "nz", "alpha3" => "nzl"],
        ["name" => "Niger", "alpha2" => "ne", "alpha3" => "ner"],
        ["name" => "Nigeria", "alpha2" => "ng", "alpha3" => "nga"],
        ["name" => "Niue", "alpha2" => "nu", "alpha3" => "niu"],
        ["name" => "Noordelijke Marianen", "alpha2" => "mp", "alpha3" => "mnp"],
        ["name" => "Noord-Korea", "alpha2" => "kp", "alpha3" => "prk"],
        ["name" => "Noorwegen", "alpha2" => "no", "alpha3" => "nor"],
        ["name" => "Norfolk", "alpha2" => "nf", "alpha3" => "nfk"],
        ["name" => "Oeganda", "alpha2" => "ug", "alpha3" => "uga"],
        ["name" => "Oekraïne", "alpha2" => "ua", "alpha3" => "ukr"],
        ["name" => "Oezbekistan", "alpha2" => "uz", "alpha3" => "uzb"],
        ["name" => "Oman", "alpha2" => "om", "alpha3" => "omn"],
        ["name" => "Oostenrijk", "alpha2" => "at", "alpha3" => "aut"],
        ["name" => "Oost-Timor", "alpha2" => "tl", "alpha3" => "tls"],
        ["name" => "Pakistan", "alpha2" => "pk", "alpha3" => "pak"],
        ["name" => "Palau", "alpha2" => "pw", "alpha3" => "plw"],
        ["name" => "Palestina", "alpha2" => "ps", "alpha3" => "pse"],
        ["name" => "Panama", "alpha2" => "pa", "alpha3" => "pan"],
        ["name" => "Papoea-Nieuw-Guinea", "alpha2" => "pg", "alpha3" => "png"],
        ["name" => "Paraguay", "alpha2" => "py", "alpha3" => "pry"],
        ["name" => "Peru", "alpha2" => "pe", "alpha3" => "per"],
        ["name" => "Pitcairneilanden", "alpha2" => "pn", "alpha3" => "pcn"],
        ["name" => "Polen", "alpha2" => "pl", "alpha3" => "pol"],
        ["name" => "Portugal", "alpha2" => "pt", "alpha3" => "prt"],
        ["name" => "Puerto Rico", "alpha2" => "pr", "alpha3" => "pri"],
        ["name" => "Qatar", "alpha2" => "qa", "alpha3" => "qat"],
        ["name" => "Réunion", "alpha2" => "re", "alpha3" => "reu"],
        ["name" => "Roemenië", "alpha2" => "ro", "alpha3" => "rou"],
        ["name" => "Rusland", "alpha2" => "ru", "alpha3" => "rus"],
        ["name" => "Rwanda", "alpha2" => "rw", "alpha3" => "rwa"],
        ["name" => "Saint-Barthélemy", "alpha2" => "bl", "alpha3" => "blm"],
        ["name" => "Saint Kitts en Nevis", "alpha2" => "kn", "alpha3" => "kna"],
        ["name" => "Saint Lucia", "alpha2" => "lc", "alpha3" => "lca"],
        ["name" => "Saint-Pierre en Miquelon", "alpha2" => "pm", "alpha3" => "spm"],
        ["name" => "Saint Vincent en de Grenadines", "alpha2" => "vc", "alpha3" => "vct"],
        ["name" => "Salomonseilanden", "alpha2" => "sb", "alpha3" => "slb"],
        ["name" => "Samoa", "alpha2" => "ws", "alpha3" => "wsm"],
        ["name" => "San Marino", "alpha2" => "sm", "alpha3" => "smr"],
        ["name" => "Saoedi-Arabië", "alpha2" => "sa", "alpha3" => "sau"],
        ["name" => "Sao Tomé en Principe", "alpha2" => "st", "alpha3" => "stp"],
        ["name" => "Senegal", "alpha2" => "sn", "alpha3" => "sen"],
        ["name" => "Servië", "alpha2" => "rs", "alpha3" => "srb"],
        ["name" => "Seychellen", "alpha2" => "sc", "alpha3" => "syc"],
        ["name" => "Sierra Leone", "alpha2" => "sl", "alpha3" => "sle"],
        ["name" => "Singapore", "alpha2" => "sg", "alpha3" => "sgp"],
        ["name" => "Sint-Helena, Ascension en Tristan da Cunha", "alpha2" => "sh", "alpha3" => "shn"],
        ["name" => "Sint-Maarten", "alpha2" => "mf", "alpha3" => "maf"],
        ["name" => "Sint Maarten", "alpha2" => "sx", "alpha3" => "sxm"],
        ["name" => "Slovenië", "alpha2" => "si", "alpha3" => "svn"],
        ["name" => "Slowakije", "alpha2" => "sk", "alpha3" => "svk"],
        ["name" => "Soedan", "alpha2" => "sd", "alpha3" => "sdn"],
        ["name" => "Somalië", "alpha2" => "so", "alpha3" => "som"],
        ["name" => "Spanje", "alpha2" => "es", "alpha3" => "esp"],
        ["name" => "Spitsbergen en Jan Mayen", "alpha2" => "sj", "alpha3" => "sjm"],
        ["name" => "Sri Lanka", "alpha2" => "lk", "alpha3" => "lka"],
        ["name" => "Suriname", "alpha2" => "sr", "alpha3" => "sur"],
        ["name" => "Swaziland", "alpha2" => "sz", "alpha3" => "swz"],
        ["name" => "Syrië", "alpha2" => "sy", "alpha3" => "syr"],
        ["name" => "Tadzjikistan", "alpha2" => "tj", "alpha3" => "tjk"],
        ["name" => "Taiwan", "alpha2" => "tw", "alpha3" => "twn"],
        ["name" => "Tanzania", "alpha2" => "tz", "alpha3" => "tza"],
        ["name" => "Thailand", "alpha2" => "th", "alpha3" => "tha"],
        ["name" => "Togo", "alpha2" => "tg", "alpha3" => "tgo"],
        ["name" => "Tokelau", "alpha2" => "tk", "alpha3" => "tkl"],
        ["name" => "Tonga", "alpha2" => "to", "alpha3" => "ton"],
        ["name" => "Trinidad en Tobago", "alpha2" => "tt", "alpha3" => "tto"],
        ["name" => "Tsjaad", "alpha2" => "td", "alpha3" => "tcd"],
        ["name" => "Tsjechië", "alpha2" => "cz", "alpha3" => "cze"],
        ["name" => "Tunesië", "alpha2" => "tn", "alpha3" => "tun"],
        ["name" => "Turkije", "alpha2" => "tr", "alpha3" => "tur"],
        ["name" => "Turkmenistan", "alpha2" => "tm", "alpha3" => "tkm"],
        ["name" => "Turks- en Caicoseilanden", "alpha2" => "tc", "alpha3" => "tca"],
        ["name" => "Tuvalu", "alpha2" => "tv", "alpha3" => "tuv"],
        ["name" => "Uruguay", "alpha2" => "uy", "alpha3" => "ury"],
        ["name" => "Vanuatu", "alpha2" => "vu", "alpha3" => "vut"],
        ["name" => "Vaticaanstad", "alpha2" => "va", "alpha3" => "vat"],
        ["name" => "Venezuela", "alpha2" => "ve", "alpha3" => "ven"],
        ["name" => "Verenigde Arabische Emiraten", "alpha2" => "ae", "alpha3" => "are"],
        ["name" => "Verenigde Staten", "alpha2" => "us", "alpha3" => "usa"],
        ["name" => "Verenigd Koninkrijk", "alpha2" => "gb", "alpha3" => "gbr"],
        ["name" => "Vietnam", "alpha2" => "vn", "alpha3" => "vnm"],
        ["name" => "Wallis en Futuna", "alpha2" => "wf", "alpha3" => "wlf"],
        ["name" => "Westelijke Sahara", "alpha2" => "eh", "alpha3" => "esh"],
        ["name" => "Wit-Rusland", "alpha2" => "by", "alpha3" => "blr"],
        ["name" => "Zambia", "alpha2" => "zm", "alpha3" => "zmb"],
        ["name" => "Zimbabwe", "alpha2" => "zw", "alpha3" => "zwe"],
        ["name" => "Zuid-Afrika", "alpha2" => "za", "alpha3" => "zaf"],
        ["name" => "Zuid-Georgia en de Zuidelijke Sandwicheilanden", "alpha2" => "gs", "alpha3" => "sgs"],
        ["name" => "Zuid-Korea", "alpha2" => "kr", "alpha3" => "kor"],
        ["name" => "Zuid-Soedan", "alpha2" => "ss", "alpha3" => "ssd"],
        ["name" => "Zweden", "alpha2" => "se", "alpha3" => "swe"],
        ["name" => "Zwitserland", "alpha2" => "ch", "alpha3" => "che"],
    ];

    /**
     * Returns all data.
     *
     * @return array
     */
    public function all(): array
    {
        return $this->data;
    }
}
